export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const FILL_ARTICLE = "FILL_ARTICLE";
export const FILL_ARTICLES = "FILL_ARTICLES";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const RESET_ARTICLE = "RESET_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FILL_CATEGORIES = "FILL_CATEGORIES";
export const FILL_CATEGORY = "FILL_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";

export const CREATE_TAG = "CREATE_TAG";
export const FETCH_TAGS = "FETCH_TAGS";
export const FILL_TAGS = "FILL_TAGS";
export const FILL_TAG = "FILL_TAG";
export const RESET_TAG = "RESET_TAG";
export const UPDATE_TAG = "UPDATE_TAG";
export const DELETE_TAG = "DELETE_TAG";

export const STATS = "STATS";
