export const CREATE_ARTICLE = "CREATE_ARTICLE";
export const FILL_ARTICLE = "FILL_ARTICLE";
export const FILL_ARTICLES = "FILL_ARTICLES";
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const RESET_ARTICLE = "RESET_ARTICLE";
export const UPDATE_ARTICLE = "UPDATE_ARTICLE";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FILL_CATEGORIES = "FILL_CATEGORIES";
export const FILL_CATEGORY = "FILL_CATEGORY";
export const RESET_CATEGORY = "RESET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
